#
# Copyright Pravega Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is used to rebuild bookkeeper branch for pravega with
# entrypoint script from pravega/docker/bookkeeper directory.
# See https://asd-nautilus-jenkins.isus.emc.com/job/bookkeeper-branch-builder/

ARG BK_VERSION=4.14.3-SNAPSHOT

FROM devops-repo.isus.emc.com:8116/apache/bookkeeper:${BK_VERSION}

WORKDIR /opt/bookkeeper

COPY entrypoint.sh /opt/bookkeeper/scripts/pravega_entrypoint.sh
COPY log4j.properties /opt/bookkeeper/conf/log4j.properties
COPY bk-sp.sh /
RUN chmod +x /bk-sp.sh
# For backwards compatibility with older operator versions
COPY entrypoint.sh /opt/bookkeeper/entrypoint.sh

RUN chmod +x -R /opt/bookkeeper/scripts/
RUN chgrp -R 0 /opt/bookkeeper && \
    chmod -R g=u /opt/bookkeeper
ENV BOOKIE_LOG_CONF=/opt/bookkeeper/conf/log4j.properties
ENV BOOKIE_LOG_DIR=/opt/bookkeeper/logs
ENV BOOKIE_ROOT_LOGGER=INFO,ROLLINGFILE
RUN sed -i 's/-Xlog:gc=info:file=\${LOG_DIR}\/\${GC_LOG_FILENAME}::filecount=5,filesize=64m//g' /opt/bookkeeper/bin/common.sh
ENTRYPOINT [ "/bin/bash", "/opt/bookkeeper/scripts/pravega_entrypoint.sh" ]
CMD ["bookie"]

HEALTHCHECK --interval=10s --timeout=60s CMD /bin/bash /opt/bookkeeper/scripts/healthcheck.sh
