#
# Copyright Pravega Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '2'
services:
  zookeeper:
    image: zookeeper:3.6.1
    ports:
      - "2181:2181"

  bookie1:
    image: asdrepo.isus.emc.com:8099/bookkeeper:0.9.1-2791.8e90eaf57
    ports:
      - "3181:3181"
    restart: always
    environment:
      ZK_URL: zookeeper:2181
      bookiePort: 3181
    links:
      - zookeeper

  bookie2:
      image: asdrepo.isus.emc.com:8099/bookkeeper:0.9.1-2791.8e90eaf57
      ports:
        - "3182:3182"
      restart: always
      environment:
        ZK_URL: zookeeper:2181
        bookiePort: 3182
      links:
        - zookeeper

  bookie3:
      image: asdrepo.isus.emc.com:8099/bookkeeper:0.9.1-2791.8e90eaf57
      ports:
        - "3183:3183"
      restart: always
      environment:
        ZK_URL: zookeeper:2181
        bookiePort: 3183
      links:
        - zookeeper

  controller:
    image: asdrepo.isus.emc.com:8099/pravega:${TAG}
    ports:
      - "9090:9090"
      - "10080:10080"
    command: controller
    environment:
      WAIT_FOR: zookeeper:2181
      ZK_URL: zookeeper:2181
      REST_SERVER_PORT: 10080
      JAVA_OPTS: |
        -Dcontroller.service.rpc.listener.port=9090
        -Xmx1024m
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
      SERVICE_HOST_IP: segmentstore
    links:
      - zookeeper

  segmentstore:
    image: asdrepo.isus.emc.com:8099/pravega:${TAG}
    ports:
      - "12345:12345"
    command: segmentstore
    privileged: true
    environment:
      WAIT_FOR: bookie1:3181,bookie2:3182,bookie3:3183
      TIER2_STORAGE: "ECSCHUNK"
      ECSCHUNK_CONFIGURI: "http://10.245.128.121:9939"
      ECSCHUNK_BUCKET: "pravega-bucket"
      ECSCHUNK_PREFIX: "pravega-tier2"
      ZK_URL: zookeeper:2181
      CONTROLLER_URL: tcp://${HOST_IP}:9092
      JAVA_OPTS: |
        -Dpravegaservice.service.published.host.nameOrIp=${HOST_IP}
        -Dbookkeeper.ensemble.size=2
        -Dbookkeeper.ack.quorum.size=2
        -Dbookkeeper.write.quorum.size=2
        -Dpravegaservice.cache.size.max=2684354560
        -Xmx2560m
        -XX:MaxDirectMemorySize=4g
        -XX:OnError="kill -9 p%"
        -XX:+ExitOnOutOfMemoryError
        -XX:+CrashOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
    links:
      - zookeeper
      - bookie1
      - bookie2
      - bookie3
